//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sugestoes_02_01.VO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesCampanhas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesCampanhas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sugestoes_02_01.VO.Resources.ResourcesCampanhas", typeof(ResourcesCampanhas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data final da campanha.
        /// </summary>
        internal static string campanhas_dat_fim {
            get {
                return ResourceManager.GetString("campanhas_dat_fim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data final da campanha obrigatório.
        /// </summary>
        internal static string campanhas_dat_fim_required {
            get {
                return ResourceManager.GetString("campanhas_dat_fim_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inicial da campanha.
        /// </summary>
        internal static string campanhas_dat_ini {
            get {
                return ResourceManager.GetString("campanhas_dat_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inicial da campanha obrigatório.
        /// </summary>
        internal static string campanhas_dat_ini_required {
            get {
                return ResourceManager.GetString("campanhas_dat_ini_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID criar campanha.
        /// </summary>
        internal static string campanhas_id_criar_campanha {
            get {
                return ResourceManager.GetString("campanhas_id_criar_campanha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID criar campanha obrigatório.
        /// </summary>
        internal static string campanhas_id_criar_campanha_required {
            get {
                return ResourceManager.GetString("campanhas_id_criar_campanha_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID escolhe vencedor.
        /// </summary>
        internal static string campanhas_id_escolhe_vencedor {
            get {
                return ResourceManager.GetString("campanhas_id_escolhe_vencedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID escolhe vencedor obrigatório.
        /// </summary>
        internal static string campanhas_id_escolhe_vencedor_required {
            get {
                return ResourceManager.GetString("campanhas_id_escolhe_vencedor_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID funcionário.
        /// </summary>
        internal static string campanhas_id_funcionario {
            get {
                return ResourceManager.GetString("campanhas_id_funcionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID funcionário obrigatório.
        /// </summary>
        internal static string campanhas_id_funcionario_required {
            get {
                return ResourceManager.GetString("campanhas_id_funcionario_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da campanha.
        /// </summary>
        internal static string campanhas_nome {
            get {
                return ResourceManager.GetString("campanhas_nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da campanha obrigatório.
        /// </summary>
        internal static string campanhas_nome_required {
            get {
                return ResourceManager.GetString("campanhas_nome_required", resourceCulture);
            }
        }
    }
}
