//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sugestoes_02_01.VO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesFuncionarios {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesFuncionarios() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sugestoes_02_01.VO.Resources.ResourcesFuncionarios", typeof(ResourcesFuncionarios).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF do funcionário.
        /// </summary>
        internal static string funcionarios_CPF {
            get {
                return ResourceManager.GetString("funcionarios_CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF do funcionário obrigatório.
        /// </summary>
        internal static string funcionarios_CPF_required {
            get {
                return ResourceManager.GetString("funcionarios_CPF_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login do funcionário.
        /// </summary>
        internal static string funcionarios_login {
            get {
                return ResourceManager.GetString("funcionarios_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login do funcionário obrigatório.
        /// </summary>
        internal static string funcionarios_login_required {
            get {
                return ResourceManager.GetString("funcionarios_login_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse campo é utilizado para o login no sistema.
        /// </summary>
        internal static string funcionarios_login_tooltip {
            get {
                return ResourceManager.GetString("funcionarios_login_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do funcionário.
        /// </summary>
        internal static string funcionarios_nome {
            get {
                return ResourceManager.GetString("funcionarios_nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do funcionário obrigatório.
        /// </summary>
        internal static string funcionarios_nome_required {
            get {
                return ResourceManager.GetString("funcionarios_nome_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o nome completo do funcionário.
        /// </summary>
        internal static string funcionarios_nome_tooltip {
            get {
                return ResourceManager.GetString("funcionarios_nome_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        internal static string funcionarios_senha {
            get {
                return ResourceManager.GetString("funcionarios_senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha obrigatória.
        /// </summary>
        internal static string funcionarios_senha_required {
            get {
                return ResourceManager.GetString("funcionarios_senha_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha deve conter 8 caracteres.
        /// </summary>
        internal static string funcionarios_senha_tooltip {
            get {
                return ResourceManager.GetString("funcionarios_senha_tooltip", resourceCulture);
            }
        }
    }
}
