//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sugestoes_02_01.VO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesCampanha_has_Funcionarios {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesCampanha_has_Funcionarios() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sugestoes_02_01.VO.Resources.ResourcesCampanha_has_Funcionarios", typeof(ResourcesCampanha_has_Funcionarios).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID campanha.
        /// </summary>
        internal static string campanha_has_funcionarios_id_campanha {
            get {
                return ResourceManager.GetString("campanha_has_funcionarios_id_campanha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID funcionário.
        /// </summary>
        internal static string campanha_has_funcionarios_id_funcionario {
            get {
                return ResourceManager.GetString("campanha_has_funcionarios_id_funcionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID funcionário obrigatório.
        /// </summary>
        internal static string campanha_has_funcionarios_id_funcionario_required {
            get {
                return ResourceManager.GetString("campanha_has_funcionarios_id_funcionario_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID campanha obrigatório.
        /// </summary>
        internal static string narios_id_campanha_required {
            get {
                return ResourceManager.GetString("narios_id_campanha_required", resourceCulture);
            }
        }
    }
}
